version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  fastapi:
    build: .
    environment:
      - SERVICE=fastapi
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - ./data:/app/data

  streamlit:
    build: .
    environment:
      - SERVICE=streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    volumes:
      - ./data:/app/data

volumes:
  qdrant_storage: