services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/ready"]
      interval: 5s
      timeout: 3s
      retries: 5

  init_embed:
    build: .
    environment:
      - SERVICE=embed
    depends_on:
      qdrant:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    command: ["python", "scripts/embed_and_upsert_qdrant.py"]

  fastapi:
    build: .
    environment:
      - SERVICE=fastapi
    ports:
      - "8000:8000"
    depends_on:
      qdrant:
        condition: service_healthy
    volumes:
      - ./data:/app/data

  streamlit:
    build: .
    environment:
      - SERVICE=streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    volumes:
      - ./data:/app/data

volumes:
  qdrant_storage:
